# Generated by Django 4.2.18 on 2025-04-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_documento_usuari_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplar',
            name='centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='biblioteca.centre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='exclos_prestec',
            field=models.BooleanField(default=False),
        ),
    ]
