# Generated by Django 4.2.18 on 2025-10-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_autor_editorial_alter_cataleg_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llibre',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='llibre',
            name='llengua',
        ),
        migrations.RemoveField(
            model_name='llibre',
            name='lloc',
        ),
        migrations.RemoveField(
            model_name='llibre',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='revista',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='revista',
            name='llengua',
        ),
        migrations.RemoveField(
            model_name='revista',
            name='lloc',
        ),
        migrations.RemoveField(
            model_name='revista',
            name='pais',
        ),
        migrations.AddField(
            model_name='cataleg',
            name='editorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.editorial'),
        ),
        migrations.AddField(
            model_name='cataleg',
            name='llengua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.llengua'),
        ),
        migrations.AddField(
            model_name='cataleg',
            name='lloc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cataleg',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.pais'),
        ),
    ]
